// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tdn.Db.Contexts;

#nullable disable

namespace backend_cs.Migrations
{
    [DbContext(typeof(CampaignContext))]
    [Migration("20260727103217_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Tdn.Db.Entities.CharacterData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("character_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GroupId")
                        .HasColumnType("int")
                        .HasColumnName("group_id");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("int")
                        .HasColumnName("owner_id");

                    b.Property<int>("TemplateId")
                        .HasColumnType("int")
                        .HasColumnName("template_id");

                    b.Property<string>("UUID")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("TemplateId");

                    b.ToTable("character", (string)null);
                });

            modelBuilder.Entity("Tdn.Db.Entities.CharacterItemData", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("int")
                        .HasColumnName("character_id");

                    b.Property<int>("ItemId")
                        .HasColumnType("int")
                        .HasColumnName("item_id");

                    b.Property<int>("Amount")
                        .HasColumnType("int")
                        .HasColumnName("amount");

                    b.HasKey("CharacterId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("character_item", (string)null);
                });

            modelBuilder.Entity("Tdn.Db.Entities.CharacterSkillData", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("int")
                        .HasColumnName("character_id");

                    b.Property<int>("SkillId")
                        .HasColumnType("int")
                        .HasColumnName("skill_id");

                    b.HasKey("CharacterId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("character_skill", (string)null);
                });

            modelBuilder.Entity("Tdn.Db.Entities.CharlistData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("template_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GroupId")
                        .HasColumnType("int")
                        .HasColumnName("group_id");

                    b.Property<string>("UUID")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("charlist_template", (string)null);
                });

            modelBuilder.Entity("Tdn.Db.Entities.GroupData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("group_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Icon")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("photo_link");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("group", (string)null);
                });

            modelBuilder.Entity("Tdn.Db.Entities.ItemData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("item_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GroupId")
                        .HasColumnType("int")
                        .HasColumnName("group_id");

                    b.Property<string>("UUID")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("item", (string)null);
                });

            modelBuilder.Entity("Tdn.Db.Entities.NoteData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("note_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AdditionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("addition_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("CharacterId")
                        .HasColumnType("int")
                        .HasColumnName("character_id");

                    b.Property<int>("GroupId")
                        .HasColumnType("int")
                        .HasColumnName("group_id");

                    b.Property<string>("Header")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("header");

                    b.Property<DateTime>("ModifyDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("modified_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("ModifyDate"));

                    b.Property<string>("ShortDescription")
                        .HasColumnType("longtext")
                        .HasColumnName("short_description");

                    b.Property<string>("UUID")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("GroupId");

                    b.ToTable("note", (string)null);
                });

            modelBuilder.Entity("Tdn.Db.Entities.NoteKeywordData", b =>
                {
                    b.Property<int>("NoteId")
                        .HasColumnType("int")
                        .HasColumnName("note_id");

                    b.Property<string>("Keyword")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("keyword");

                    b.HasKey("NoteId", "Keyword");

                    b.ToTable("note_keyword", (string)null);
                });

            modelBuilder.Entity("Tdn.Db.Entities.QuestAssignmentData", b =>
                {
                    b.Property<int>("QuestId")
                        .HasColumnType("int")
                        .HasColumnName("quest_id");

                    b.Property<int>("CharacterId")
                        .HasColumnType("int")
                        .HasColumnName("character_id");

                    b.HasKey("QuestId", "CharacterId");

                    b.HasIndex("CharacterId");

                    b.ToTable("quest_assignment", (string)null);
                });

            modelBuilder.Entity("Tdn.Db.Entities.QuestData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("quest_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GroupId")
                        .HasColumnType("int")
                        .HasColumnName("group_id");

                    b.Property<string>("Header")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("header");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<string>("UUID")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("UUID")
                        .IsUnique();

                    b.ToTable("quest", (string)null);
                });

            modelBuilder.Entity("Tdn.Db.Entities.SkillData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("skill_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GroupId")
                        .HasColumnType("int")
                        .HasColumnName("group_id");

                    b.Property<string>("UUID")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("skill", (string)null);
                });

            modelBuilder.Entity("Tdn.Db.Entities.UserCharacterData", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int>("GroupId")
                        .HasColumnType("int")
                        .HasColumnName("group_id");

                    b.Property<int>("CharacterId")
                        .HasColumnType("int")
                        .HasColumnName("character_id");

                    b.Property<bool?>("CanWrite")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("can_write");

                    b.HasKey("UserId", "GroupId", "CharacterId");

                    b.ToTable("user_character", (string)null);
                });

            modelBuilder.Entity("Tdn.Db.Entities.UserGroupData", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int>("GroupId")
                        .HasColumnType("int")
                        .HasColumnName("group_id");

                    b.Property<bool?>("IsAdmin")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_admin");

                    b.HasKey("UserId", "GroupId");

                    b.ToTable("user_group", (string)null);
                });

            modelBuilder.Entity("Tdn.Db.Entities.CharacterData", b =>
                {
                    b.HasOne("Tdn.Db.Entities.GroupData", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tdn.Db.Entities.CharlistData", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("Tdn.Db.Entities.CharacterItemData", b =>
                {
                    b.HasOne("Tdn.Db.Entities.CharacterData", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tdn.Db.Entities.ItemData", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Tdn.Db.Entities.CharacterSkillData", b =>
                {
                    b.HasOne("Tdn.Db.Entities.CharacterData", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tdn.Db.Entities.SkillData", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Tdn.Db.Entities.CharlistData", b =>
                {
                    b.HasOne("Tdn.Db.Entities.GroupData", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Tdn.Db.Entities.ItemData", b =>
                {
                    b.HasOne("Tdn.Db.Entities.GroupData", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Tdn.Db.Entities.NoteData", b =>
                {
                    b.HasOne("Tdn.Db.Entities.CharacterData", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Tdn.Db.Entities.GroupData", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Tdn.Db.Entities.NoteKeywordData", b =>
                {
                    b.HasOne("Tdn.Db.Entities.NoteData", "Note")
                        .WithMany("Keywords")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Note");
                });

            modelBuilder.Entity("Tdn.Db.Entities.QuestAssignmentData", b =>
                {
                    b.HasOne("Tdn.Db.Entities.CharacterData", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tdn.Db.Entities.QuestData", "Quest")
                        .WithMany()
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Quest");
                });

            modelBuilder.Entity("Tdn.Db.Entities.QuestData", b =>
                {
                    b.HasOne("Tdn.Db.Entities.GroupData", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Tdn.Db.Entities.SkillData", b =>
                {
                    b.HasOne("Tdn.Db.Entities.GroupData", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Tdn.Db.Entities.UserCharacterData", b =>
                {
                    b.HasOne("Tdn.Db.Entities.UserGroupData", "Group")
                        .WithMany()
                        .HasForeignKey("UserId", "GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Tdn.Db.Entities.NoteData", b =>
                {
                    b.Navigation("Keywords");
                });
#pragma warning restore 612, 618
        }
    }
}
