// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tdn.Db.Contexts;

#nullable disable

namespace game_systems_service.Migrations
{
    [DbContext(typeof(GameSystemsContext))]
    [Migration("20260904131025_AddSystemIcon")]
    partial class AddSystemIcon
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Tdn.Db.Entities.SystemAdminData", b =>
                {
                    b.Property<string>("SystemId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("system_id");

                    b.Property<string>("SubjectType")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("subject_type");

                    b.Property<string>("SubjectId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("subject_id");

                    b.HasKey("SystemId", "SubjectType", "SubjectId");

                    b.HasIndex("SystemId", "SubjectType", "SubjectId")
                        .IsUnique();

                    b.ToTable("system_admins", (string)null);
                });

            modelBuilder.Entity("Tdn.Db.Entities.SystemData", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("Icon")
                        .HasColumnType("longtext")
                        .HasColumnName("icon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("systems", (string)null);
                });

            modelBuilder.Entity("Tdn.Db.Entities.SystemVersionData", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("created_at");

                    b.Property<string>("SnapshotId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("snapshot_id");

                    b.Property<string>("SystemId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("system_id");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("SystemId", "Version")
                        .IsUnique();

                    b.ToTable("system_versions", (string)null);
                });

            modelBuilder.Entity("Tdn.Db.Entities.SystemAdminData", b =>
                {
                    b.HasOne("Tdn.Db.Entities.SystemData", null)
                        .WithMany()
                        .HasForeignKey("SystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tdn.Db.Entities.SystemVersionData", b =>
                {
                    b.HasOne("Tdn.Db.Entities.SystemData", null)
                        .WithMany()
                        .HasForeignKey("SystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
