global:
  scrape_interval: 15s
  evaluation_interval: 15s
  metric_name_validation_scheme: legacy

# services:
#   metrics:
#     enabled: true
#     prometheus:
#       enabled: true

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']


  - job_name: 'api-gateway'
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: [ 'api-gateway:5000' ]

  - job_name: 'campaign-service'
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: [ 'campaign-service:8080' ]

  - job_name: 'users-service'
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: [ 'users-service:8080' ]

  - job_name: 'policy-service'
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: [ 'policy-service:8080' ]

  - job_name: 'auth-service'
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: [ 'auth-service:8080' ]

  # - job_name: 'mysql-exporter'
  #   static_configs:
  #     - targets: ['mysql-exporter:9104']
  #   scrape_interval: 30s

  # - job_name: 'mongodb-exporter'
  #   static_configs:
  #     - targets: ['mongodb-exporter:9216']
  #   scrape_interval: 30s