version: '3'

services:
  admin-panel:
    build: .
    container_name: admin-panel
    networks:
      - backend_backend-network
    ports:
      - "${ADMIN_PORT:-8081}:80"
    env_file:
      - ./.env

networks:
  backend_backend-network:
    external: true
